### ISSUE TITLE
Build the Game Summary page

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#103]
We have a request for a game summary page. Somewhere you can see a history of your past trades or easily screenshot for clout. 

![image](https://github.com/cartridge-gg/rollyourown/assets/3332646/53dea0e1-71b2-41c8-be50-3c06ca2d88e4)

Think it's a great idea, lets build it. 

---

https://github.com/cartridge-gg/rollyourown/assets/3332646/cf48f629-dcb2-4d69-bfb6-cf286eb1bff7

---

**Desktop**

<img width="728" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/d41cb7ae-35b1-4494-90cb-ab7ebde082f6">

Note: there is a state change on the button when it is selected. Background fill -> to border
Note: we're moving the back button so that it's closer to the rest of the UI 

**Mobile**

<img width="230" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/4699fef2-dd76-4cb7-bbcd-115e7eea469d">

Note: Since the game state bar is a button now, i modified the proportions of it a bit. It's bigger

---

Pages - [Desktop](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4033%3A175565&mode=design&t=v9m0i3u6Pr6J2wlk-1) [Mobile](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4060%3A153939&mode=design&t=v9m0i3u6Pr6J2wlk-1)

**Comment by clicksave** [comment]
Update: 

New title 

<img width="649" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/2cc1823b-ac8e-4a35-8a86-047a9b9039af">

**Comment by akhercha** [comment]
Hey, can try this one!

**Comment by clicksave** [comment]
> Hey, can try this one!

All yours! but think it makes sense to hold off on this until Val is done migrating to 0.3.0 (soon™)

There have been some design changes that will impact this ticket anyways. so let me get started on those will have an update here soon

**Comment by akhercha** [comment]
Oke makes sense, I'll wait for updates before going further then! Thanks :)

**Comment by akhercha** [comment]
Made something like this for the moment:

https://github.com/cartridge-gg/rollyourown/assets/22559023/8e169089-d146-495f-af86-9ca1e54de5cd

I'll pause until I have updates!
