### ISSUE TITLE
Remove horizontal scroll on mobile (inventory page)

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#106]
observed on iPhone, Safari

**Description**

Theres some unwanted horizontal scrolling on mobile. scroll should be vertical only

---

https://github.com/cartridge-gg/rollyourown/assets/3332646/e518472b-4ea6-4b38-9757-1f658a9208e4

---

- [ ] Remove horiztontal scroll on the inventory page

**Comment by notV4l** [comment]
outdated
