### ISSUE TITLE
Fix header issues on mobile

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#113]
When navigating to a page that requires a back button the header jumps around

https://github.com/cartridge-gg/rollyourown/assets/3332646/95e54dec-b1f0-435c-9088-ae9ffa1683a6

---

- [ ] Elements should be fixed in place. 

<img width="1244" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/562a3ff6-25c3-4e7e-88c5-638534097a3e">

---

There are also some sizing/ui improvements that I'd like to make 

<img width="386" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/1015c6f1-3696-484d-946b-a55ecc4a3938">

![Photo Jul 31 2023, 13 58 33](https://github.com/cartridge-gg/rollyourown/assets/3332646/a486788a-2f43-4d8e-ab6c-aeb5f380a9d9)

- [ ] Back button should be left aligned
- [ ] dot dot button should be right aligned
- [ ] game status bar should be center aligned
- [ ] header should be taller. 40px -> 48 px [Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=666%3A65900&mode=design&t=b6ovHOG3rAj4gGCC-1)
- [ ] Header doesn't scale to fit large numbers, so we should have some kind of solution for that. If we need to show $3,500,000 maybe we render it as 3.5m.. etc. 
- [ ] Replace clock icon with a calendar icon
![Generic Icons](https://github.com/cartridge-gg/rollyourown/assets/3332646/d6ebb886-0099-48dc-8fc3-5e03aaffdbc3)
- [ ] Replace '9/10' text with '9' i.e. just show the day

**Comment by notV4l** [comment]
outdated
