### ISSUE TITLE
Update the menu button on mobile

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#116]
ATM there is no way to return to the game after you navigate to the leaderboard page, we don't have a working chat page, and the profile button 'shinobi' doesn't show relevant information. 

My recommendation is to remove the non functional options for the time being, leaving only the media player, and account button.

![Photo Jul 31 2023, 16 30 05](https://github.com/cartridge-gg/rollyourown/assets/3332646/2ab22beb-e06a-4c63-9b5a-96ce08b6f6c9)

---

<img width="1766" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/f0a36437-c9db-4b2b-8e1c-06604874310e">

[Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4304%3A131422&mode=design&t=b6ovHOG3rAj4gGCC-1)

---

**Account button**

We're using burner wallets, so they don't have usernames the way cartridge controllers do. in light of this I'l love to update the button text from 'Shinobi' to the wallet address. 

Clicking on this button should open up a log out modal. 

---

I would love to add a 'Credits' option which shows the contributors to the game. If you've worked on this game and aren't listed here lets add a line for you as well! (if you want) 

---

Additionally, the mockups add a translucent background overlay to the menu, as well as a border that creates some space for the menu items. I'd love to include these visual updates in this batch of work. 

[Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2465%3A116221&mode=design&t=b6ovHOG3rAj4gGCC-1)

---

- [ ] Remove extra non-functional buttons from the menu (mobile)
- [ ] Add a credits button
- [ ] Add log out modal
- [ ] Update the UI

**Comment by notV4l** [comment]
can we close this one ?

**Comment by clicksave** [comment]
yessr
