### ISSUE TITLE
 Build a Tutorial pattern 

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#124]
Lets add a tutorial pattern to give new players a way to familiarize themselves with the game/rules. I imagine this can/will change a bit as the game evolves. Simplest strategy is to have it appear in a modal

https://github.com/cartridge-gg/rollyourown/assets/3332646/4031aaee-95fc-4ab6-bfaf-897fac5f566a

---

**Resources**

[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4550%3A24857&mode=design&t=pYNr4pZvIvCNxUcr-1)
[Components](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4480%3A27129&mode=design&t=pYNr4pZvIvCNxUcr-1)

---

Note: This design moves the 'create burner' button to the header

Will follow up with responsive comps

**Comment by clicksave** [comment]
Mobile Iterations

<img width="1747" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/0b78f4de-9a57-4a6d-b5bd-583fa4fd8653">

---

[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4570%3A33128&mode=design&t=pYNr4pZvIvCNxUcr-1)

**Comment by broody** [comment]
Tutorial pattern looks great, there are some additional bells n whistles when traveling ;) @clicksave take a look here: https://rollyourown-git-fork-notv4l-addtutorial.preview.cartridge.gg/

**Comment by clicksave** [comment]
Really like the audio on random events! but I think the Gang one conflicts a bit with the sound track. Could we update that? something like this instead?

[1911-reload-6248.mp3.zip](https://github.com/cartridge-gg/rollyourown/files/12621494/1911-reload-6248.mp3.zip)

If I'm being picky I'd also like the siren for the cops to be shorter, my recommendation

[police-siren-one-loop-loop-able-104019.mp3.zip](https://github.com/cartridge-gg/rollyourown/files/12621636/police-siren-one-loop-loop-able-104019.mp3.zip)

---

Think the animation when traveling to different events is cool, and it reinforces where you're going which I like but I think the execution could be a little better should we do something like that. feels a powerpoint effect. Lets hold off on that for now

Mind making these changes? @notV4l

**Comment by clicksave** [comment]
A few more notes on the tutorial modal

<img width="375" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/3ed6ceec-bfc6-4612-97ec-322669d8acf5">

- [ ] Padding on mobile is a little off, and can we use the same translucent background color on mobile that we do on desktop?

<img width="168" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/fbefbe14-8658-4a32-8972-368352a75304">

- [ ] The dot dot buttons feel too big to me, and two dot sizes not perfectly center aligned (theres some movement when you navigate between pages. 

Use these. I have them at 16x16px in the mockups

![dot_inactive](https://github.com/cartridge-gg/rollyourown/assets/3332646/a004315c-6672-4723-ba72-fe63659179c1)
![dot_active](https://github.com/cartridge-gg/rollyourown/assets/3332646/c74676e1-f970-4981-9751-08ef73509d42)

**Comment by clicksave** [comment]
[Dot SVGs.zip](https://github.com/cartridge-gg/rollyourown/files/12621754/Dot.SVGs.zip)

**Comment by clicksave** [comment]
> * Padding on mobile is a little off

Oh weird, im only observing this in the browser when I switch to mobile view. Looks great on my phone
