### ISSUE TITLE
Improvements to the Buy/Sell pattern

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#132]
Think this a a pretty good quality of life improvement. Have been watching people interact with the game and it seems like they get tripped up by the tabs on the buy/sell tabs. 

So lets get rid of them and have players decide whether they want to buy or sell on the location page directly

See below 

https://github.com/cartridge-gg/rollyourown/assets/3332646/48170183-da87-41a4-9d40-89cef1fc831f

Annd mobile comps

<img width="327" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/7a476b30-8ba5-42b3-ad49-5c5efae01c57">
<img width="329" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/619c5c90-9904-46e0-b62b-53bcbea27b3e">

---

You'll notice some differences. documenting here 

- [ ] Theres a reconfiguration of the input section of the market page 

<img width="605" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/b1bd535d-a3a9-4236-8bf6-13414ec5b8be">

- [ ] I added a number field for players to type the quantity of drug they want. Would be cool to add, and convenient for players

- [ ] I'm introducing 'health' to the Status Bar 

<img width="485" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/869985f6-4d00-42dc-acaa-74599d476d3b">

Note: Including this stat, forces us to render it differently on mobile. We needed the extra space anyways so here's what I came up with

<img width="602" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/ee8fb2f5-851b-4e2d-a71a-fc0bb1be5ed6">
 
---

**Resources**

[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=4755%3A41944&mode=design&t=HejezGSBaAzc44NL-1)
[Prototype](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=3576%3A128844&type=design&node-id=4755-41944&viewport=227%2C-19170%2C0.27&t=GeV7xGdLaWk7u0Mw-1&scaling=min-zoom&starting-point-node-id=4755%3A41944&show-proto-sidebar=1&mode=design)

**Comment by broody** [comment]
Resolved in https://github.com/cartridge-gg/rollyourown/pull/130
