### ISSUE TITLE
Extend the drug card hover target to the entire card

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#138]
In order to see the buy/sell buttons you currently need to hover over the specific place on the card where they appear. This should be extended to the entire card (e.g. anything within the outline that contains the title and pricing information 

https://github.com/cartridge-gg/rollyourown/assets/3332646/098bf557-56d5-4958-ba1a-85ecd32ffd73

**Comment by broody** [comment]
Resolved in https://github.com/cartridge-gg/rollyourown/pull/136
