### ISSUE TITLE
Update the inventory component

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#144]
Headers getting fat so lets doing a little reorganization. 

<img width="1709" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/73540fbf-08ac-4c96-a926-ddb6146ffbee">
<img width="531" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/47c208b2-4594-47fa-9cb5-d653ed6b2773">

This ticket moves the 'bag' tracker into the inventory component on the location page

<img width="521" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/84427747-eda9-4abb-8f0e-161aeadb1851">

--- 

Note: theres a bunch of extra stuff in these mockups thats not scoped for this ticket. will create them as separate issues

---

**Resources**
[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=5127%3A62110&mode=design&t=CAGd207jUkKi4dxi-1)

**Comment by broody** [comment]
Fixed in main
