### ISSUE TITLE
[bug] Players are disappearing from the leaderboard

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#169]
![image](https://github.com/cartridge-gg/rollyourown/assets/3332646/aa8a176a-700b-4d2a-a927-08d932b7e2d6)
<img width="1386" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/1e2153f3-fc4c-4b9d-9585-bbe06fe6d3cc">

**Comment by notV4l** [comment]
haha spotted mr JK
since we can only query all scores with a limit (actually 100) and we can't order, it only take 100 first, will raise it to 500

**Comment by broody** [comment]
Yeah good solution for now, for proper sorting we'll need to convert cash from u128 -> u64 so sqlite is sorting by integer. Can do that further down the road tho, hate to rug these hall of famers...
