### ISSUE TITLE
Modify price balancing

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#191]
Modify price balancing. right now there isn't much logic between the price controls, and after playing a bunch of rounds there are certain drugs that feel like they get better prices than others. i.e. find myself buying speed and acid a lot more than weed. 

Lets try this... design around the price discrepancy explicitly

Ludes: **15 - 105** (7x discrepancy)
Speed: **90 - 540** (6x discrepancy)
Weed: **450 - 2250** (5x discrepancy)
Acid: **1800 - 7200** (4x discrepancy)
Heroin: **5400 - 16200** (3x discrepancy)
Cocaine: **10800 - 21600** (2x discrepancy)

The main ideas represented in these numbers...

1. you can make a higher percentage of profit on the cheaper drugs
2. you can allocate more capital towards the more expensive ones.
3. It's possible to observe some overlap. (i.e. sometimes you'll see Acid cheaper than Weed)

**Comment by clicksave** [comment]
@notV4l Think you finished this, yeah?

**Comment by notV4l** [comment]
i'll set this exact figures in next version
