### ISSUE TITLE
Enable native media controls

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#192]
Per discord...

<img width="753" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/ce8d16c3-64a4-4906-b96f-c359ae6ba4dd">

https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API

**Comment by jaipaljadeja** [comment]
can i take this issue?

**Comment by clicksave** [comment]
@notV4l ?
