### ISSUE TITLE
Add inventory bar to the travel page

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#198]
We should surface this, think it'll be nice to see the drugs you own when you're looking at prices in different locations.

heads up. Looks a little different on desktop than it does on mobile 

<img width="1602" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/3a847b10-055a-4b7d-bb4f-afa4be37aacf">
<img width="541" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/f3147f2e-a9cb-410c-a26e-9de0fec3f3ba">

**Comment by akhercha** [comment]
Hey, can I pick this up?

Also, I'm not sure what are the purpose of the knife and vest buttons. 
What should happen when you click on them?
