### ISSUE TITLE
Update the Wallet/Address button

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#204]
Render the players PFP in this button (instead of their wallet address and have it trigger the profile modal. 

<img width="1630" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/bec2c3f6-d157-4288-9ea3-4f9b7bd54c9e">

<img width="1175" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/b191e81b-6b16-45c9-8466-60f418fb96ae">

On mobile button is in the dot dot menu 

<img width="464" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/898b6d31-4383-4b79-b5a2-ab5908acec74">

<img width="581" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/431345eb-1ee2-40d8-bdb4-836e95bd36ca">

**Comment by clicksave** [comment]
Resources

[Desktop Modal](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=5747%3A207032&mode=design&t=gtGpx9QSt6HgWVu3-1)
[Mobile Modal](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=5799%3A353128&mode=design&t=gtGpx9QSt6HgWVu3-1)

**Comment by clicksave** [comment]
@notV4l Need to add this on mobile

**Comment by notV4l** [comment]
> Need to add this on mobile

its ok for me on browser with mobile resolution
