### ISSUE TITLE
Changes to the Pawn Shop

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#205]
Pawn shop should appear every 5 turns as an event and allow you to upgrade an item or add an additional one. 

We should make this mandatory instead of optional. And in doing so we should remove the $$$ cost of items

<img width="1352" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/8042886f-ec8a-42da-9fa6-cd570a677693">
<img width="1350" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/138a657e-ceaa-4278-828c-d61a48c7ae4c">

When you select an item on this page you should see it appear in your inventory before pressing continue 

<img width="904" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/2d1508ae-720d-46ca-9a54-45ef2a9e9e59">

Also need to see the choice appear in the results page

<img width="1336" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/cdf9ee57-e0ab-45c4-923e-c4bbe1e6aa1c">

---

Mobile

<img width="502" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/17deb59c-da97-4221-b9f6-3d8279b39c65">

----

I've also made some changes to the card (we should surface the thing that the item does) not sure if '+1' is the best way to measure that. open to different approaches to 'stats' and how we represent them 

---

Thinking that we should wait until turn 5 to show the pawn shop and then show it every 5 turns. 

so 

5, 10, 15, 20... etc. 

We can experiment with different schedules

**Comment by clicksave** [comment]
Resources

[Pawn Shop](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=5789%3A346139&mode=design&t=gtGpx9QSt6HgWVu3-1) 

[Results page](<img width="1384" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/4dbbe0d4-2d94-4de4-b4ae-d8eeb75a5b96">)

**Comment by notV4l** [comment]
if you don't buy stuff its not a shop anymore

**Comment by clicksave** [comment]
Thats fine

**Comment by clicksave** [comment]
Will remake this ticket per our conversation
