### ISSUE TITLE
Move the name entry to a modal and fully commit to the infinite game mode

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#206]
Lets keep it simple, and present a single unified leaderboard. Name entry doesn't need to be its own page

<img width="969" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/d85b6f83-9394-41ad-b172-200642783284">

https://github.com/cartridge-gg/rollyourown/assets/3332646/9737a307-86cc-4062-80dd-20029a408976

---

Mobile 

<img width="358" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/1a238056-4e2b-47a9-97ee-59030ee85043">

**Comment by clicksave** [comment]
Resources

[Modal](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=5536%3A66519&mode=design&t=gtGpx9QSt6HgWVu3-1)

**Comment by notV4l** [comment]
we replaced modal by page with avatar selector

**Comment by clicksave** [comment]
Yep, outdated
