### ISSUE TITLE
Heart icon should change to reflect health status

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#237]
Nice to have

---

<img width="587" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/661fcf6f-404b-402b-806a-2c9657eeee57">

We have these three health icons. would be cool to have them be indicative of how much health your character has 

<img width="1522" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/f39e1c59-779c-4bfd-817b-5b9b818fdc13">

<img width="1916" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/c5444e8b-9745-4423-a9dc-cc802e32bf47">

<img width="1560" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/71ff9ad6-0a62-4b55-8023-842d3232cbd7">

--- 

Coolest thing to do here would be to have it show the actual percentage of health you have but maybe thats to niche. 

---
![Icon=Heart Empty](https://github.com/cartridge-gg/rollyourown/assets/3332646/617f4013-c4d1-420d-bb1b-ebece4886e6e)
![Icon=Heart Half](https://github.com/cartridge-gg/rollyourown/assets/3332646/48ef06fc-6b5f-4112-bf52-0b8bcd68a93d)
![Icon=Heart Full](https://github.com/cartridge-gg/rollyourown/assets/3332646/0104e508-222b-4bcf-bcf1-28a936e94e23)

**Comment by akhercha** [comment]
Hey! Taking this one as discussed with @notV4l 🫡
