### ISSUE TITLE
Add new hustlers to the PFP selector

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#261]
Let me know if you need these in a specific size (these are 36px x 36px wide)

<img width="2168" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/2406b32c-facf-4180-8dba-76c2ef9eaf6e">

---

![Person=Person M, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/dfb7fefc-41f0-4836-b691-a738117854fd)
![Person=Person M, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/c64943a2-4708-4a0d-ade9-dd47ed05e01b)
![Person=Person M, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/78d9a163-d7cc-46a2-8704-6eddea77152b)
![Person=Person M, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/0e53c73e-af6c-46d2-b79e-1161994f6252)
---
![Person=Person N, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/f260420d-117b-4a26-a17d-0c5364ee0a87)
![Person=Person N, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/8f3903c0-2b74-447d-8efc-5dca5887bf07)
![Person=Person N, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/e93fb841-f07d-4756-a7c2-4aebca920e38)
![Person=Person N, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/24865866-c627-4e2a-84d8-c3813900dd5c)
---
![Person=Person O, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/a24a280c-ebdb-408e-8151-c62af61d4f5e)
![Person=Person O, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/a7386798-834c-4215-8efb-7f251afbf8de)
![Person=Person O, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/8f7e2d30-11ed-4ec3-bad6-73b8d22617ff)
![Person=Person O, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/dc3fc4dd-2dde-4e01-844a-455e8d914dcd)
---
![Person=Person P, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/f7060389-09a0-446b-8858-77f49d9b9ff7)
![Person=Person P, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/1e28c267-98a4-4108-a3e7-18c48b998b41)
![Person=Person P, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/dd85d39f-f70b-44a2-8b27-0449c9ec4c45)
![Person=Person P, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/ef6f2c2f-96c8-423b-8b09-756111bc534b)
---
![Person=Person Q, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/a6b26bad-b99a-4521-81e9-3c29eed059ed)
![Person=Person Q, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/b0fdbade-ccd4-4001-92df-e9b81f318036)
![Person=Person Q, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/40459918-ac1d-4426-9140-dac06e83427d)
![Person=Person Q, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/f27410cb-c0a9-472e-a5b3-d53f06fc820f)
---
![Person=Person R, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/80d04a16-b0a5-4590-a915-8b2d7f668d8e)
![Person=Person R, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/95d21b0b-5ad4-4426-81e0-b15b0cf2106e)
![Person=Person R, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/4a2bbf50-8f11-4d9b-876e-94fc0bc4d902)
![Person=Person R, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/b2afd603-f156-4495-a390-2fdea7483dd7)
---
![Person=Person S, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/ccd62583-1fcd-47a0-8346-5c9e6f007f59)
![Person=Person S, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/21a57003-263d-4dac-a940-60cc7aba80c8)
![Person=Person S, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/70078471-daf4-4af7-8587-dc6299bee001)
![Person=Person S, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/4343733b-aca1-445f-b1c1-83991f5e177e)
---
![Person=Person T, Color=Green, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/f699d685-de57-4959-923f-8d88454076d6)
![Person=Person T, Color=Green, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/462f8435-1453-46a4-9930-871a52107b7d)
![Person=Person T, Color=Yellow, Crown=False](https://github.com/cartridge-gg/rollyourown/assets/3332646/a0b2f4ea-2937-4877-9431-d0ebfe399816)
![Person=Person T, Color=Yellow, Crown=True](https://github.com/cartridge-gg/rollyourown/assets/3332646/3ceb730c-5b14-4e6b-aaf9-e76192bbcbc1)
---

[New Hustlers.zip](https://github.com/cartridge-gg/rollyourown/files/13419484/New.Hustlers.zip)

**Comment by notV4l** [comment]
@clicksave i need 60x60 like previous avatars plz

**Comment by clicksave** [comment]
[60px.zip](https://github.com/cartridge-gg/rollyourown/files/13476980/60px.zip)
Here ya go!
