### ISSUE TITLE
Update border radii to pixel corners

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#33]
The corners of the primary buttons have been built with this really nice rounded-corner pixel effect. We'd like extend that treatment to all places where rounded corners exist in the app. 

<img width="136" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/8bfbc8df-3e10-4005-b6ee-ca471673bbb9">

<img width="1167" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/713ec54f-2079-4349-9290-4c2ba7f66c58">

To achieve this effect a svg is cut into four quadrants and applied it to each corner. 

Task: 
- Apply pixel corners to the secondary buttons and status bar in the header
- Apply pixel corners to the inventory bar
- Apply pixel corners to the 'My games' section on the Home Page
- Apply pixel corners to the location toggle on the Travel Page

Figma:
[Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78515&t=eze7jiCs7cICbCpf-1)

SVG:
![Corners](https://github.com/cartridge-gg/rollyourown/assets/3332646/4595662b-0eea-4ea3-bca8-02c7cdaa823b)

**Comment by SNikhill** [comment]
@cwdwdy 
May I please request that I have this issue?

**Comment by cwdwdy** [comment]
@SNikhill Hell yes you can

**Comment by SNikhill** [comment]
Thank you for assigning this.

I shall work on it this weekend.

**Comment by SNikhill** [comment]
By the @clicksave if you need this with priority then, please let me know.

**Comment by clicksave** [comment]
@SNikhill going to reassign this ticket, thanks

**Comment by SNikhill** [comment]
I see. Sorry, I couldn't focus on it at the moment.
