### ISSUE TITLE
Reformat the side panel illustrations

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#34]
Early designs for RYO called for for full bleed images on desktop to augment the page content (see below) 

<img width="1511" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/6bf5c0c1-ef75-4f22-bf1b-debfceea38ee">

---

This has since changed and new designs call for the illustration to be center aligned (with some vertical padding on the top)

<img width="1830" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/07ddcde4-c9d9-41a3-8f5b-f39e4b70fe81">

Note: We don't have the final set of illustrations yet, but they will all follow this format [placeholders can be found here](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2187%3A107767&t=eze7jiCs7cICbCpf-1)
Note: These illustrations are still omitted in the mobile view of the game

---

Figma: 
[Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78515&t=eze7jiCs7cICbCpf-1)

Task: 
- Update the [Home Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78515&t=eze7jiCs7cICbCpf-1) to include the new image format
- Update the [New Game Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78755&t=eze7jiCs7cICbCpf-1) to include the new image format
- Update the [Pending Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A79025&t=eze7jiCs7cICbCpf-1) to include the new image format
- Update the [Lobby Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78940&t=eze7jiCs7cICbCpf-1) to include the new image format
- Update the [Inventory Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=974%3A77337&t=eze7jiCs7cICbCpf-1) to include the new image format
- Update the [Turn Summary Page](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A79495&t=eze7jiCs7cICbCpf-1) to include the new image format

**Comment by notV4l** [comment]
how about mobile version ?

**Comment by zoemeriet** [comment]
Can I take this issue ?

**Comment by clicksave** [comment]
> how about mobile version ?

Hey good Q, sorry could been clearer in the spec. Mobile comps omit the side panel illustration. Can be found here. 

[Figma](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=946%3A78516&t=xfhAmS7lZwPwZKxv-1)

<img width="928" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/3c75ddcb-3261-4db8-a949-4b4604e7b160">
<img width="608" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/def0cb76-dcd4-451a-a07f-0b4d4f58bdb1">
