### ISSUE TITLE
Add a sound toggle to the header

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#35]
RYO will have music and sound effects. players will need a way to toggle that on and off. So we're putting a Sound Toggle in the header. Check it out

https://github.com/cartridge-gg/rollyourown/assets/3332646/48cccdf7-f162-4b46-b116-9b45284d74d2

Here are the designs

[Header](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=666%3A65900&t=eze7jiCs7cICbCpf-1)

[Button](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2187%3A76380&t=eze7jiCs7cICbCpf-1)

[Icons](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2187%3A76379&t=eze7jiCs7cICbCpf-1)

[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2188%3A78441&t=eze7jiCs7cICbCpf-1)

Prototype: [Desktop](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=703%3A71995&type=design&node-id=2188-78986&viewport=485%2C-16519%2C0.45&scaling=min-zoom&starting-point-node-id=2188%3A78441), [Mobile](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=703%3A71995&type=design&node-id=2193-80146&viewport=485%2C-16519%2C0.45&scaling=min-zoom&starting-point-node-id=2193%3A79625&show-proto-sidebar=1)

---

Task: 
- Add a mute button to the header this will appear on all pages

Note: The header is rendered a little differently on mobile (horizontal and vertical padding is removed with some slightly different button detailing) 

Note: On mobile the hover state is replaced by a tap state

Note: Sound should be on by default

**Comment by sparqet** [comment]
Can I also take this one ?

**Comment by clicksave** [comment]
Definitely

**Comment by notV4l** [comment]
i'll do this one

**Comment by notV4l** [comment]
i can't export icons from figma :/

**Comment by clicksave** [comment]
> i can't export icons from figma :/

Hey! give it another shot updated the permissions. 
Here are the SVGs though just in case

SVGs:
![Music=Off](https://github.com/cartridge-gg/rollyourown/assets/3332646/43d76d26-0df8-4abd-83a6-f64c609a0141)
![Music=On](https://github.com/cartridge-gg/rollyourown/assets/3332646/dd2cd877-50a2-4194-9c37-5d3fa8909922)
