### ISSUE TITLE
Improve Input behavior

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#36]
We have a pretty normal input atm, uses the classic '|' cursor. Would be cool to do something a little more retro. Take a look at the video below. 

https://github.com/cartridge-gg/rollyourown/assets/3332646/11b9ea06-5129-4bec-a213-0a69f81a7ed0

---
Task: Update the input cursor to a flashing block instead of the a vertical pipe

Figma: 
[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2196%3A80696&t=eze7jiCs7cICbCpf-1)
[Prototype](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=703%3A71995&type=design&node-id=2196-80696&viewport=485%2C-16519%2C0.45&scaling=min-zoom&starting-point-node-id=2196%3A80696)
[Input States](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=1799%3A75602&t=eze7jiCs7cICbCpf-1)

SVG: 
![Cursor](https://github.com/cartridge-gg/rollyourown/assets/3332646/ef54f1f2-c8b6-4a0e-89c5-5017b8fa24d2)

**Comment by sparqet** [comment]
Hi may I take this one ?

**Comment by clicksave** [comment]
> Hi may I take this one ?

Absolutely, thanks!

**Comment by notV4l** [comment]
can i ?

**Comment by tarrencev** [comment]
@notV4l go for it!
