### ISSUE TITLE
Add feedback to number selectors

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#37]
Right now the number inputs are a little lackluster and could benefit from better feedback. 

See https://rollyourown.preview.cartridge.gg/create

--- 

Here's a design that introduces some hover states for the arrows and has the field's value flash to signal that its changed. 

https://github.com/cartridge-gg/rollyourown/assets/3332646/8f67679c-c995-482b-8811-f5c463c5b148

Figma: 
[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=1741%3A76931&t=6EdikY6P0X79lXNd-1)
[Button States](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=883%3A86616&t=6EdikY6P0X79lXNd-1)
[Field States](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=1770%3A85568&t=6EdikY6P0X79lXNd-1)
[Prototype](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=703%3A71995&type=design&node-id=1741-76931&viewport=485%2C-16519%2C0.45&scaling=min-zoom&starting-point-node-id=1741%3A76931&show-proto-sidebar=1)

---

Task: 
Improve feedback for the number field

Note: This ticket is really about the behavior of the arrows but would be cool to have a way to type the value of the field as well

**Comment by zoemeriet** [comment]
Can I take this issue ?
