### ISSUE TITLE
Improve Dropdown behavior

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#38]
Lets build some custom dropdowns. Would be nice if these were more aligned with the rest of the game UI (see below) 

https://github.com/cartridge-gg/rollyourown/assets/3332646/df866023-3b5b-4adf-be5b-96d1614d54bf

---

Designs
[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2217%3A78803&t=6EdikY6P0X79lXNd-1)
[Prototype](https://www.figma.com/proto/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?page-id=703%3A71995&type=design&node-id=2217-80010&viewport=485%2C-16519%2C0.45&scaling=min-zoom&starting-point-node-id=1746%3A87382)
[Hover States](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=1770%3A75312&t=6EdikY6P0X79lXNd-1)
[Dropdown](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=1746%3A80760&t=6EdikY6P0X79lXNd-1)

---

Task: 
Update the dropdown UI/behavior 

Note: We'll also want to apply this design to the 'Duration' field

**Comment by NewtonFernandis** [comment]
Hey @clicksave, I will work on this could you please assign this to me?

**Comment by zoemeriet** [comment]
Hello! Can I take this issue ?

**Comment by tarrencev** [comment]
Yes please!
