### ISSUE TITLE
Reskin the Chakra Date selector

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#52]
We may decided to modify the 'Starts' field to be a date selector instead of the simple dropdown that exists now. 

Nothing fancy, just a reskin of the selector that already exists in Chakra. 

https://chakra-ui.com/docs/components/input#input-methods-other-than-text

<img width="832" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/e5080294-2229-47f8-8cb7-74e3d51f9484">

Resources
[Mockup](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2636%3A107045&t=xfhAmS7lZwPwZKxv-1)
Components
[Date/Time Field](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2574%3A100916&t=xfhAmS7lZwPwZKxv-1) [Button States](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2576%3A101308&t=xfhAmS7lZwPwZKxv-1) [Selector](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2576%3A102118&t=xfhAmS7lZwPwZKxv-1)

Note: The mobile version of this input as an entirely different pattern. Don't have designs for that view quite yet. We should find out whether or not it's using Native UI elements before we proceed

**Comment by notV4l** [comment]
After investingating a bit, chakra don't have a dedicated DatePicker component, it uses Input component with a type :
`<Input type="datetime-local">`  therefore it can't be customized.

One solution could be using a Datepicker component.
Maybe put this issue aside since it's not sure you want to use a datepicker instead of dropdown

**Comment by tarrencev** [comment]
Hmm @notV4l thats a good point thanks for doing the research. Lets backlog this for now, since it seems like a pretty significant increase in scope
