### ISSUE TITLE
Build the Buy/Sell Page

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#62]
**Description**

Each drug will have its own 'Market' page where you can exchange money for supply or visa versa. You can access this page by clicking on the drug on the location page. 

This is part of the core game loop. Prices fluctuate turn to turn and your goal as a player is to arbitrage them and make a profit. 

https://github.com/cartridge-gg/rollyourown/assets/3332646/c9c88163-846a-4af8-bce3-8b8b9cc849b5

---

**Requirements**

- [ ] Build a Market page for each of the six drugs (Ludes, Speed, Weed, Acid, Heroin, Cocaine)

<img width="1221" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/17b39e1f-ea15-4c61-88e1-7d0b592ec5e3">

- [ ] Players will be able to click 'max buy' and 'max sell' to quickly navigate the amounts
- [ ] Players will able to incrimentally change the quanity with the arrows to the right and left of the horizontal progress bar thing

<img width="836" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/0a17655a-9942-4d05-b6b7-fb0e659158b6">

- [ ] On the market page the home button is replaced by a back button which will take you back to the location page
- [ ] The 'bag number' and the amount of money you have in the header change depending on your activity

<img width="1943" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/d5bbed1e-a650-4c4a-85dc-1d011aee6523">

- [ ] We likely will add additional feedback when players buy/sell things but for now lets just get this page working
- [ ] Make it responsive 

<img width="459" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/c30214d3-b8db-406c-8301-e102463eb4a3">

---

**Resources**

[Pages](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=703%3A72541&t=a5hGDf2fGxkxek5h-1)

[Mobile Comp](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=703%3A73815&t=a5hGDf2fGxkxek5h-1)

[Illustrations](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2832%3A137707&t=a5hGDf2fGxkxek5h-1)

**Comment by notV4l** [comment]
can i ?
