### ISSUE TITLE
Build the Location Pages

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#64]
**Description**

We have a finalized set of illustrations for the location pages! lets add them to the game. 

<img width="852" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/7eea6e77-563a-4a6a-b3e4-d1a1c33038b0">

The full flow for goes like this 

At location -> End Turn -> Select new location -> Random event -> summary page (confirmed on starknet) -> New location

See the following for a general idea 

https://github.com/cartridge-gg/rollyourown/assets/3332646/497b123d-ed0c-4d3d-b5ff-3c43cc2de15a

- [ ] Note: On Mobile the illustrations are omitted

<img width="348" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/6e5921cc-8e9d-4148-9cfb-8adc3fb0f149">

---

**Requirements**

- [ ] Build a page for each location (distinct title & illustration)
- [ ] Build the responsive pages
- [ ] Have the travel flow advance the turn (i.e. After traveling Day 2 turns into Day 3)  

---

**Resources**
Figma Pages - [Desktop](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2832%3A139045&t=N7dnchy7jmI1cA8V-1)
Illustrations - [Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2832%3A140571&t=N7dnchy7jmI1cA8V-1)

**Comment by notV4l** [comment]
i already started to make this changes while doing #62

**Comment by clicksave** [comment]
All yours! 

> i already started to make this changes while doing #62
