### ISSUE TITLE
Build the Chat/Activity Page

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#65]
**Description**

A big part of the game is going to be communicated via the chat feature. 

It will contain system messages, random events information, and of course a chat log where players can communicate. The first iteration of this page is accessible via the header. Check it out

https://github.com/cartridge-gg/rollyourown/assets/3332646/24d30d4b-ed28-4a4c-b154-6b6b941fda28

---

**Details**

_Player Messages_

Initially, players will be assigned a random avatar for the duration of the game, when they communicate it will but displayed along with their message.

<img width="1360" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/27c3142f-6dd7-489d-b814-1eba46c80378">

Like most chat apps, other players avatars will be left aligned to their messages and your avatars will be right aligned 

<img width="1564" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/79b30701-3508-4857-891b-714f9c764daf">

_New Bar_

There will also be a new bar, that places a reference point in the chat feed separating messages you've seen from the ones that are new. 

<img width="728" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/bddbecc5-72b4-410b-a976-347f1637404f">

If new messages exist, the chat button in the header will change its appearance (become yellow). 

<img width="1875" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/5d4b4b1b-6d59-4740-94ec-ac5e75861e71">

It's default state (when no new messages exist) is green 

<img width="1578" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/879cae17-fec9-4fa0-a1b8-9385ccab21d2">

_Random Events_

We'll initially support three kinds of random events. Hacked, Mugged, and Arrested. When one of these occurs it should be broadcast to the chat along appended with that players username. 

If this occurs to you, the username should be replaced with 'You' (i.e. You were Hacked)

<img width="1140" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/35c37dc9-c533-4e5c-8375-795eaf67d11b">

_System Messages_

We'll also want to show system messages, i.e. if a player joins the game, if the game starts, and if when the game ends

<img width="1139" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/086d238f-b75d-49c5-b606-3d59c7a6c9f0">

_Empty State_ 

If no one has said anything, and no messages exist, we might want to consider adding an empty state. 

<img width="1148" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/1bfbfe17-9aae-4e44-a911-024bb3f04511">

---

**Audio**

We'd like to add some unique audio feedback for new messages. When one is received the player should hear a notification. Of these, my favorite is 1b_Pager_Send_Soft_5 but feel free to experiment. 

[PAGER_SFX.zip](https://github.com/cartridge-gg/rollyourown/files/11804453/PAGER_SFX.zip)

---

**Responsiveness**

There are some design constraints for mobile devices that should be considered. See below. Same logic, but the chat button now appears in a menu. 

https://github.com/cartridge-gg/rollyourown/assets/3332646/92a51b9c-5565-494c-a4eb-e1e3753abbaa

---

**Resources**

Pages - [Desktop](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2909%3A127498&t=ZCIyHnKKwnaIsyXg-1) [Mobile](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2909%3A127499&t=ZCIyHnKKwnaIsyXg-1)

Components - [Link](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=666%3A65993&t=ZCIyHnKKwnaIsyXg-1)

NOTE: This is kind of a complicated feature, so consider this a first pass. We anticipate that the scope of this page will change over time, and im sure there are a few things I havent anticipated

**Comment by clicksave** [comment]
Connected with @broody and it seems like hooking up the Chat feature will be a larger undertaking. So lets limit the scope of this ticket strickly to the front end.

**Comment by zoemeriet** [comment]
I’m working on this issue, and a have some questions :
- I couldn’t find the avatar component, it is not implemented yet ? (I don’t want to duplicate the code if it already exists)
- Thanks to the Layout component, we can had a background Image, they came from « https://static.cartridge.gg/games/dope-wars/ryo/something.png », were can I found the image for the Chat page ?

**Comment by broody** [comment]
> * I couldn’t find the avatar component, it is not implemented yet ? (I don’t want to duplicate the code if it already exists)
Mmm I don't think it's implemented. Could be a simple component that takes an account address as input and returns an avatar icon

>  were can I found the image for the Chat page ?
I see it [here](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2909-127498&mode=design&t=43GwXU8I63ydOKy9-0), it's a static image tho. @clicksave do we have a gif for this? Or maybe we can use the static base pager and do the scrolling text in CSS

**Comment by clicksave** [comment]
Cool, down with that approach as well. here's a static version of the pager without the text

![pager](https://github.com/cartridge-gg/rollyourown/assets/3332646/9a53fa11-0d08-4d62-bddd-45a049353bf9)


> > * I couldn’t find the avatar component, it is not implemented yet ? (I don’t want to duplicate the code if it already exists)
> 
> Mmm I don't think it's implemented. Could be a simple component that takes an account address as input and returns an avatar icon
> 
> > were can I found the image for the Chat page ?
> 
> I see it [here](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=2909-127498&mode=design&t=43GwXU8I63ydOKy9-0), it's a static image tho. @clicksave do we have a gif for this? Or maybe we can use the static base pager and do the scrolling text in CSS

**Comment by clicksave** [comment]
Comfortable rolling with the static image for now as well. or maybe we add some logic where if theres a new message you show the gif and if not you default to the static.

Think these should be size appropriately but let me know if not. 

![pager_animated](https://github.com/cartridge-gg/rollyourown/assets/3332646/8cafa01e-1453-41d9-aba3-506f74d7d155)
