### ISSUE TITLE
Add back button to the buy/sell, and travel pages  

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#94]
**Current**
<img width="1511" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/ee557e9f-20a7-47dd-a29c-f72d71bb8905">

**Requested**

<img width="1053" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/5b781129-1325-46fb-9eb1-45cea0000d43">

---

Travel page also needs a back button

---

Pages:
https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=3657%3A204627&mode=design&t=gXnCltkAdj4JrQw9-1

**Comment by broody** [comment]
Resolved https://github.com/cartridge-gg/rollyourown/commit/8fe4769afda292b9080039d1fd9b80f0b181e8a2
