### ISSUE TITLE
Remove 'Buy' slider when the player can't afford an item

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/rollyourown#96]
<img width="817" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/2ccc93a1-86b1-4471-8fd3-0bb7bddd9286">

- [x] Update the copy to say 'You can't afford this' 
- [x] Remove the BUY slider when a play is not allowed to interact with it
- [ ] Ideally, players won't be able to scroll on this page
- [x] Buy/Sell tabs feel disabled to me, can you update the colors

---

Page

https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=3657%3A204627&mode=design&t=gXnCltkAdj4JrQw9-1

**Comment by broody** [comment]
The scroll issue requires a layout change and is a larger issue, will address it in another PR
